services:
  mysql-server:
    build: ./mysql_init
    ports:
      - 3306:3306
    container_name: mysql_container
    volumes:
      - mysql-server_db:/var/lib/mysql
  
  # express-server:
  #   build: ./
  #   restart: always
  #   command: node ./app.js;
  #   depends_on:
  #     - mysql-server
  #   ports:
  #     - 3000:3000
  #   container_name: express_container

volumes:
  mysql-server_db:
    driver: local